# Generated by Django 4.1.5 on 2023-03-10 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emp_leave',
            name='date',
        ),
        migrations.AddField(
            model_name='emp_leave',
            name='enddate',
            field=models.DateField(blank=True, null=True, verbose_name='enddate (yyyy-mm-dd)'),
        ),
        migrations.AddField(
            model_name='emp_leave',
            name='startdate',
            field=models.DateField(blank=True, null=True, verbose_name='startdate (yyyy-mm-dd)'),
        ),
    ]
